model:
  checkpoint_path: "./models/aura_flow_0.3.bnb_nf4.safetensors"
  pretrained_model_name_or_path: fal/AuraFlow-v0.3

  dtype: bfloat16

  denoiser:
    use_flash_attn: true

peft:
  config:
    type: lora
    rank: 4
    alpha: 1.0
    dropout: 0.0

    dtype: bfloat16

  include_keys:
    - "attn.w2"
    - regex: .*single_layers\.\d+\.w1[qkvo]
    - ".mlp."
    - ".mlpX."
  exclude_keys: ["text_encoder", "vae", "t_embedder", "final_linear", ".mod"]

dataset:
  folder: "data/sfw_0.1k/images"
  num_repeats: 4
  batch_size: 2

  bucket_base_size: 1024
  step: 128
  min_size: 384
  do_upscale: false

optimizer:
  name: "schedulefree.RAdamScheduleFree"
  # name: "bitsandbytes.optim.AdamW8bit"
  args:
    lr: 0.001

scheduler:
  # name: "torch.optim.lr_scheduler.ConstantLR"
  # args: {}

tracker:
  project_name: "auraflow-lora-1"
  loggers:
    - wandb

saving:
  strategy:
    per_epochs: 1
    per_steps: null
    save_last: true

  callbacks:
    - type: "safentensors" # or "hf_hub" to push to hub
      name: "test-lora"
      save_dir: "./output/lora"

preview:
  strategy:
    per_epochs: 1
    per_steps: 10

  callbacks:
    - type: "local"
      save_dir: "./output/lora/preview"

  data:
    path: "./configs/preview.yml"

seed: 42
num_train_epochs: 10

trainer:
  # debug_mode: "1step"

  gradient_checkpointing: true

  torch_compile: true
  torch_compile_args:
    mode: max-autotune
    fullgraph: true
  fp32_matmul_precision: "medium"
